Fix: Readme and Contributing Guide
ZupIT/horusec-operator pull request #120
Opened 2021-11-24 14:43 UTC by jessica-tw

Signed-off-by: jessica-tw <jessica.olinda@zup.com.br>

**- What I did**
- Fixed Readme file.
- Added new Contributing Guide.

**- How to verify it**

**- Description for the changelog**

2021-11-29 14:48 UTC, matheusalcantarazup requested changes

2021-11-29 14:48 UTC, matheusalcantarazup commented on CONTRIBUTING.md
> +<p align="center" margin="20 0"><img src="assets/pr-template.PNG" alt="architecture" width="100%" style="max-width:100%;"/></p>
This image was not added on commit.

2021-11-30 16:09 UTC, nathanmartinszup commented on CONTRIBUTING.md
> +> #### 2.1.   [**Developer Certificate of Origin**](#developer-certificate-of-origin)
Redirect not working

2021-11-30 16:09 UTC, nathanmartinszup commented on CONTRIBUTING.md
> +### 3. [**How to contribute?**](#how-to-contribute?)
Redirect not working

2021-11-30 16:09 UTC, nathanmartinszup commented on CONTRIBUTING.md
> +> #### 3.3. [**Add new feature, bug fixing or improvement**](#add-new-feature-bugfixing-or-improvement)
Redirect not working

2021-11-30 16:09 UTC, nathanmartinszup commented on CONTRIBUTING.md
> +> #### 3.4.  [**Pull Request's approval**](#pull-request-approval)
Redirect not working

2021-11-30 16:09 UTC, nathanmartinszup commented on CONTRIBUTING.md
> +> #### 3.5.   [**After your pull request's approval**](#after-your-pull-request-approval)
Redirect not working

2021-11-30 16:09 UTC, nathanmartinszup commented on CONTRIBUTING.md
>  - [**Charts**](https://github.com/ZupIT/charlescd/tree/main/circle-matcher)
Redirecting to a charles cd repostitory. I think this repository it's unnecessary. @wiliansilvazup What do you think?

2021-11-30 16:09 UTC, nathanmartinszup commented on CONTRIBUTING.md
>  - [**Kotlin**](https://github.com/ZupIT/horusec-tree-sitter-kotlin)
Empty repository, necessary? @wiliansilvazup

2021-11-30 16:09 UTC, nathanmartinszup commented on CONTRIBUTING.md
> +- Do you have any question about Horusec? Send to our [**mailing list**](horusec@zup.com.br).
Mail list returning not found

2021-11-30 16:09 UTC, nathanmartinszup commented
Rebase branch with main

2021-12-10 17:11 UTC, nathanmartinszup approved these changes

2021-12-10 17:15 UTC, merged